name: x-Maven build workflow-x
on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      app-name:
        required: true
        type: string

jobs:
  maven:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: "temurin"
      - name: Build with Maven
        run: ./mvnw -B package -DskipTests
        working-directory: applications/${{ env.APP_NAME }}
