name: x-Build and analyze workflow-x
on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      app-name:
        required: true
        type: string

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: "temurin"
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ inputs.app-name }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        working-directory: applications/${{ inputs.app-name }}
  
  hadolint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        id: hadolint
        with:
          dockerfile: applications/${{ inputs.app-name }}/Dockerfile
          failure-threshold: warning
      - name: Print out the results
        env:
          results: ${{ steps.hadolint.outputs.results }}
        run: echo "$results"