name: Publish workflow

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      app-name:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: "temurin"
      - name: Publish package
        run: mvn -D deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}