name: hello-rest-service-ci

on:
  workflow_dispatch:
  push:
    paths:
      - "applications/hello-rest-service/**"
      - ".github/workflows/hello-rest-service-ci.yaml"
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    uses: ./.github/workflows/_app-maven-build.yaml
    with:
      java-version: "17"
      app-name: "hello-rest-service"

  test:
    needs: ["build"]
    uses: ./.github/workflows/_app-build-analyze.yaml
    with:
      java-version: "17"
      app-name: "hello-rest-service"
    secrets: inherit
