name: hello-rest-service-ci

on:
  workflow_dispatch:
  push:
    paths:
      - "applications/hello-rest-service/**"
      - ".github/workflows/hello-rest-service-ci.yaml"
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  maven:
    uses: ./.github/workflows/_app-maven-build.yaml
    with:
      java-version: "17"
      app-name: "hello-rest-service"

  sonarcloud:
    uses: ./.github/workflows/_app-build-analyze.yaml
    with:
      java-version: "17"
      app-name: "hello-rest-service"
  # test:
  #   runs-on: ubuntu-latest
  #   needs: ["build"]

  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0 # Shallow clones
  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: "17"
  #         distribution: "microsoft"
  #     - name: Cache SonarCloud packages
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.sonar/cache
  #         key: ${{ runner.os }}-sonar
  #         restore-keys: ${{ runner.os }}-sonar
  #     - name: Cache Maven packages
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.m2
  #         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
  #         restore-keys: ${{ runner.os }}-m2
  #     - name: Build and analyze
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #       run: ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
  #       working-directory: applications/hello-rest-service
